const currentYear = new Date().getFullYear();
const myYearsOld = currentYear - 2003;
const xpTime = currentYear - 2019;

const components = {
  mySocialNetwork: 'Minhas redes Sociais',
  welcome: 'Seja Bem Vindo',
  myPortfolio: 'Meu Portfólio',
  myProjects: 'Meus projetos',
  historyWithIT: 'História com TI',
  historyWithITContent: `No inicio de 2019 iniciei meus estudos na área de desenvolvimento web na ETEC, de lá para até aqui eu desenvolvi dezenas de projetos, fiz amizades na área de TI e me desenvolvi bastante profissionalmente e mentalmente. Aprendi sobre lógica, banco de dados, design, marketing, etc. Atualmente sou um desenvolvedor Full Stack com foco na web. No menu na aba ‘Projetos’ tem projetos desenvolvidos por mim, como: api rest, clonagem de sites, consumo de api, sistema de login e algumas ideias que tive e desenvolvi.`,
  projectsDeveloped: "Projetos desenvolvidos",
  clickHere: 'Clique aqui',
  currently: `No momento presente ${currentYear}, tenho ${myYearsOld} anos, estou atuando há ${xpTime} com desenvolvimento web, sou técnico em informática para internet formado pela ETEC Guilhermina (Praia Grande). Tenho boa comunicação e pró-atividade. Desenvolvi diversos projetos que estão em exposição no github.`,
  myName: "João Félix",
  startedOnProgramming: '04/02/2019',
  ITStudent: 'Estudante de programação desde ',
  felixDeveloper: 'Félix Developer',
  fullStackDeveloper: 'Full Stack Developer',

  viewProject: 'Ver projeto',
  monoProject: 'Projetos monopólios',
  backProject: 'Projetos Back End',
  frontProject: 'Projetos Front End',
  title: {
    tese: 'Tese Mobilidade.',
    quiz: 'Jogo Quiz (JS).',
    dashboard: 'DashBoard Programathor.',
    backOurtube: 'Back-End Ourtube "Youtube"',
    frontOurtube: 'Front-End Ourtube "Youtube"',
    next: 'Projeto Next "IA" feito com JS.',
    felixflix: 'Projeto ReactJs Felixflix.',
    starWars: 'Projeto consumo de APi com React.',
    fsNode: 'Upload de arquivos com Node JS.',
    apiTsExpress: 'API Rest com Typescript & express.',
    apiJsExpress: 'API Rest com Javascript & express.',
    api: "API NodeJS com mongoDB.",
    apiJSMysql: 'Api node com Javascript e MySQL.',
    apiTSMysql: 'Api node com Typescript e MySQL.',
    customWare: 'Custom Ware Co. (php).',
    loginSimulator: "Simulador de Login (JS).",
    loginPHP: 'Sistema de Login com PHP.',
    backendLogin: 'Sistema de login Back End',
    serverSocket: 'Servidor de comunicação socket',
    serverSocketAuth: 'Servidor de comunicação com autenticação',
    privateMarket: 'Mercado Privado',
    frontEndLogin: 'Sistema de login Front End',
    clientSocket: 'Client de comunicação socket',
  },
  content: {
    tese: "Projeto de sistema de ônibus responsivo feito com Bootstrap.",
    backOurtube: 'Sistema que imita algumas funções básicas do youtube',
    frontOurtube: 'Crie canais, se inscreva, veja vídeos, pesquise e mais...',
    quiz: "Projeto feito para testar seus conhecimentos em relação aos animais.",
    dashboard: "Esse projeto apresenta o dashboard do Programathor, usei Grid Layout.",
    felixflix: 'Projeto clone "netflix" aprendendo a usar display Flex.',
    next: "Sistema desenvolvido para simular 'IA', o next é simples.",
    starWars: 'Projeto desenvolvido para aprender a consumir dados de Api.',
    fsNode: "Sistema de upload de arquivos com Nodejs (PDF, docs, imagens,pastas, etc.).",
    apiJsExpress: 'APi desenvolvida com Javascript & express usando Json como banco de dados.',
    apiTsExpress: 'APi desenvolvida com Typescript & express usando Json como banco de dados.',
    api: "Api desenvolvida com express muito útil para usar como base.",
    apiJSMysql: 'Servidor node integrado com MySQl (banco de dados) usando JS.',
    apiTSMysql: 'Servidor node integrado com MySQl (banco de dados) usando TS.',
    loginSimulator: "Projeto que simula um sistema de login de forma simples (apenas simulador).",
    loginPHP: "Sistema de login (real) feito com PHP, muito útil para entender como funciona.",
    customWare: "Projeto completo simulando um e-commerce feito com PHP, HTML, Css e Bootstrap.",
    backendLogin: 'Sistema nodeJS para autenticação de usuários com jsonwebtoken',
    serverSocket: 'Servidor de comunicação socket para conversa em real time',
    serverSocketAuth: 'Servidor de comunicação socket para usuários autenticados real time',
    privateMarket: 'Projeto clone "Mercado Livre" descomplicando display Grid',
    frontEndLogin: 'Sistema ReactJS de autenticação de usuários com jsonwebtoken',
    clientSocket: 'Client de comunicação socket para conversa em real time',
  },
  home: ' Home',
  history: ' História',
  aboutMe: ' Sobre mim',
  wantAWebSite: ' Quero um site',
  projects: 'Projetos',
  contact: ' Contato',
  default: 'Padrão',
  dark: 'Escuro',
  defineTheme: 'Defina o tema',
  outOfOfficeHours: 'Fora do horário de serviço',
  goodMorning: 'Bom%20dia%20João!',
  goodAfternoon: 'Boa%20tarde%20João!'
}

export default components;