const Projects = {
  viewProject: 'Ver projeto',
  monoProject: 'Projetos monopólios',
  backProject: 'Projetos Back End',
  frontProject: 'Projetos Front End', 
  title: {
    tese: 'Tese Mobilidade.',
    quiz: 'Jogo Quiz (JS).',
    dashboard: 'DashBoard Programathor.',
    next: 'Projeto Next "IA" feito com JS.',
    felixflix: 'Projeto ReactJs Felixflix.',
    starWars: 'Projeto consumo de APi com React.',
    fsNode: 'Upload de arquivos com Node JS.',
    apiTsExpress: 'API Rest com Typescript & express.',
    apiJsExpress: 'API Rest com Javascript & express.',
    api: "API NodeJS com mongoDB.",
    apiJSMysql: 'Api node com Javascript e MySQL.',
    apiTSMysql: 'Api node com Typescript e MySQL.',
    customWare: 'Custom Ware Co. (php).',
    loginSimulator: "Simulador de Login (JS).",
    loginPHP: 'Sistema de Login com PHP.',
    backendLogin: 'Sistema de login Back-end',
    serverSocket: 'Servidor de comunicação socket',
    serverSocketAuth: 'Servidor de comunicação com autenticação',
  },
  content: {
    tese: "Projeto de sistema de ônibus responsivo feito com Bootstrap.",
    quiz: "Projeto feito para testar seus conhecimentos em relação aos animais.",
    dashboard: "Esse projeto apresenta o dashboard do Programathor, usei Grid Layout.",
    felixflix: 'Projeto clone "netflix" aprendendo a usar display Flex.',
    next: "Sistema desenvolvido para simular 'IA', o next é simples.",
    starWars:  'Projeto desenvolvido para aprender a consumir dados de Api.',
    fsNode: "Sistema de upload de arquivos com Nodejs (PDF, docs, imagens,pastas, etc.).",
    apiJsExpress: 'APi desenvolvida com Javascript & express usando Json como banco de dados.',
    apiTsExpress: 'APi desenvolvida com Typescript & express usando Json como banco de dados.',
    api: "Api desenvolvida com express muito útil para usar como base.",
    apiJSMysql: 'Servidor node integrado com MySQl (banco de dados) usando JS.',
    apiTSMysql: 'Servidor node integrado com MySQl (banco de dados) usando TS.',
    loginSimulator: "Projeto que simula um sistema de login de forma simples (apenas simulador).",
    loginPHP: "Sistema de login (real) feito com PHP, muito útil para entender como funciona.",
    customWare: "Projeto completo simulando um e-commerce feito com PHP, HTML, Css e Bootstrap.",
    backendLogin: 'Sistema nodeJS para autenticação de usuários com jsonwebtoken',
    serverSocket: 'Servidor de comunicação socket para conversa em real time',
    serverSocketAuth: 'Servidor de comunicação socket para usuários autenticados real time',
  }
}

export default Projects;